services:
  mongodb:
    image: mongo:latest
    ports:
      - 27020:27017 
    volumes:
      - dbdata:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: master
      MONGODB_INITDB_ROOT_PASSWORD: secret
  mongocore.api:
    build: 
      context: .
      dockerfile: MongoCore.API/Dockerfile
    ports:
      - 5076:5076
    depends_on:
      - mongodb
      
volumes:
  dbdata: