services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017 
    volumes:
      - mongodata:/data/db
    env_file:
      - env/development.env
  mongocore.api:
    build: 
      context: .
      dockerfile: MongoCore.API/Dockerfile
    ports:
      - 5076:5076
    depends_on:
      - mongodb
      
volumes:
  mongodata: