apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongocore-app-deployment
spec:
  selector:
    matchLabels:
      app: mongocore-app
      tier: backend
  template:
    metadata:
      labels:
        app: mongocore-app
        tier: backend
    spec:
      containers:
      - name: mongocore-node
        image: preetbasson/mongocore-api
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
